---
abstract: 'Programmatic interface to the Perl debugging API'
author:
  - 'Anthony Brummett <brummett@cpan.org>'
build_requires:
  File::Basename: '0'
  IO::Pipe: '0'
  Test::Builder: '0'
  Test::More: '0'
  lib: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Devel-Chitin
requires:
  Carp: '0'
  Digest::MD5: '0'
  Exporter: '0'
  IO::File: '0'
  PadWalker: '0'
  Scalar::Util: '0'
  base: '0'
  strict: '0'
  vars: '0'
  warnings: '0'
resources:
  repository: https://github.com/amb43790/Devel-Chitin.git
version: '0.03'
